In [20]:
import pandas as pd

df = pd.read_csv("netflix_titles.csv", encoding="utf-8")
df

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,NaN,United States,"September 25, 2021",2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm..."
1,s2,TV Show,Blood & Water,NaN,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t..."
2,s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",NaN,"September 24, 2021",2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act...",To protect his family from a powerful drug lor...
3,s4,TV Show,Jailbirds New Orleans,NaN,NaN,NaN,"September 24, 2021",2021,TV-MA,1 Season,"Docuseries, Reality TV","Feuds, flirtations and toilet talk go down amo..."
4,s5,TV Show,Kota Factory,NaN,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, Romantic TV Shows, TV ...",In a city of coaching centers known to train I...
...,...,...,...,...,...,...,...,...,...,...,...,...
8802,s8803,Movie,Zodiac,David Fincher,"Mark Ruffalo, Jake Gyllenhaal, Robert Downey J...",United States,"November 20, 2019",2007,R,158 min,"Cult Movies, Dramas, Thrillers","A political cartoonist, a crime reporter and a..."
8803,s8804,TV Show,Zombie Dumb,NaN,NaN,NaN,"July 1, 2019",2018,TV-Y7,2 Seasons,"Kids' TV, Korean TV Shows, TV Comedies","While living alone in a spooky town, a young g..."
8804,s8805,Movie,Zombieland,Ruben Fleischer,"Jesse Eisenberg, Woody Harrelson, Emma Stone, ...",United States,"November 1, 2019",2009,R,88 min,"Comedies, Horror Movies",Looking to survive in a world taken over by zo...
8805,s8806,Movie,Zoom,Peter Hewitt,"Tim Allen, Courteney Cox, Chevy Chase, Kate Ma...",United States,"January 11, 2020",2006,PG,88 min,"Children & Family Movies, Comedies","Dragged from civilian life, a former superhero..."
8806,s8807,Movie,Zubaan,Mozez Singh,"Vicky Kaushal, Sarah-Jane Dias, Raaghav Chanan...",India,"March 2, 2019",2015,TV-14,111 min,"Dramas, International Movies, Music & Musicals",A scrappy but poor boy worms his way into a ty...

In [21]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8807 entries, 0 to 8806
Data columns (total 12 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   show_id       8807 non-null   object
 1   type          8807 non-null   object
 2   title         8807 non-null   object
 3   director      6173 non-null   object
 4   cast          7982 non-null   object
 5   country       7976 non-null   object
 6   date_added    8797 non-null   object
 7   release_year  8807 non-null   int64
 8   rating        8803 non-null   object
 9   duration      8804 non-null   object
 10  listed_in     8807 non-null   object
 11  description   8807 non-null   object
dtypes: int64(1), object(11)
memory usage: 825.8+ KB

In [22]:
df.describe()

       release_year
count   8807.000000
mean    2014.180198
std        8.819312
min     1925.000000
25%     2013.000000
50%     2017.000000
75%     2019.000000
max     2021.000000

In [23]:
df.columns

Index(['show_id', 'type', 'title', 'director', 'cast', 'country', 'date_added',
       'release_year', 'rating', 'duration', 'listed_in', 'description'],
      dtype='object')

In [24]:
df.dtypes

show_id         object
type            object
title           object
director        object
cast            object
country         object
date_added      object
release_year     int64
rating          object
duration        object
listed_in       object
description     object
dtype: object

In [25]:
df.isnull().sum()

show_id            0
type               0
title              0
director        2634
cast             825
country          831
date_added        10
release_year       0
rating             4
duration           3
listed_in          0
description        0
dtype: int64

In [26]:
df.duplicated().sum()

np.int64(0)

In [27]:
df.nunique()

show_id         8807
type               2
title           8807
director        4528
cast            7692
country          748
date_added      1767
release_year      74
rating            17
duration         220
listed_in        514
description     8775
dtype: int64

In [28]:
#check the particular raw, to check the data whether it is in other language or not
df[df.show_id=='s5023']

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
5022,s5023,Movie,반드시 잡는다,Hong-seon Kim,Baek Yoon-sik,South Korea,"February 28, 2018",2017,TV-MA,110 min,"Dramas, International Movies, Thrillers",After people in his town start turning up dead...

In [29]:
# let's check the length of the characters, so we can give this the varchar length in SQl while creating the table

# There will be null values inside the data so form max(df.show_id.str.len()), we have to use like this: max(df.show_id.dropna().str.len()) 
print("The length of the char in [show_id] column is: " + str(max(df.show_id.dropna().str.len())))
print("The length of the char in [type] column is: " + str(max(df.type.dropna().str.len())))
print("The length of the char in [title] column is: " + str(max(df.title.dropna().str.len())))
print("The length of the char in [director] column is: " + str(max(df.director.dropna().str.len())))
print("The length of the char in [cast] column is: " + str(max(df.cast.dropna().str.len())))
print("The length of the char in [country] column is: " + str(max(df.country.dropna().str.len())))
print("The length of the char in [date_added] column is: " + str(max(df.date_added.dropna().str.len())))
print("The length of the char in [rating] column is: " + str(max(df.rating.dropna().str.len())))
print("The length of the char in [duration] column is: " + str(max(df.duration.dropna().str.len())))
print("The length of the char in [listed_in] column is: " + str(max(df.listed_in.dropna().str.len())))
print("The length of the char in [description] column is: " + str(max(df.description.dropna().str.len())))

The length of the char in [show_id] column is: 5
The length of the char in [type] column is: 7
The length of the char in [title] column is: 104
The length of the char in [director] column is: 208
The length of the char in [cast] column is: 771
The length of the char in [country] column is: 123
The length of the char in [date_added] column is: 19
The length of the char in [rating] column is: 8
The length of the char in [duration] column is: 10
The length of the char in [listed_in] column is: 79
The length of the char in [description] column is: 248

In [ ]:
import sqlalchemy as sal

engine = sal.create_engine('mssql://writeyourSQLDashboardName/master?driver=writeYourSQLODBCDRIVER')
conn=engine.connect()

Now load the data to the Microsoft SQL server

Also handling the foreihn characters with the use of NVARCHAR

In [46]:
from sqlalchemy.types import NVARCHAR

df.to_sql(
    "df_netflix_raw",
    engine,
    if_exists="append",
    index=False,
    dtype={
        "title": NVARCHAR(200),
        "director": NVARCHAR(250),
        "cast": NVARCHAR(1000),
        "country": NVARCHAR(150),
        "description": NVARCHAR(500),
    }
)

107